### ISSUE TITLE
How to evaluate the error

### ISSUE THREAD

**Issue by Guan2014** [navganti/SIVO#3]
Hi @navganti 
I use evo to evaluate the translation error(%) and rotation error(deg/m), but my results differ from yours in the paper of SIVO. can you tell me what evaluation tool you use？

**Comment by navganti** [comment]
Hi @PYGUAN - I actually used the same metrics as the KITTI dataset odometry challenge. Their code was available online, and I am hosting a slightly modified version of it here: https://github.com/navganti/kitti_scripts/tree/master/odometry/devkit. The modification to the script allowed for the error evaluation on sequences 00-10 automatically, and also was able to overlay the results from different versions of SIVO.

From the KITTI [website](http://www.cvlibs.net/datasets/kitti/eval_odometry.php): "From all test sequences, our evaluation computes translational and rotational errors for all possible subsequences of length (100,...,800) meters. The evaluation table below ranks methods according to the average of those values, where errors are measured in percent (for translation) and in degrees per meter (for rotation)."

**Comment by Guan2014** [comment]
Hi @navganti
Thank you! That really helped me.

**Comment by navganti** [comment]
@PYGUAN anytime, glad to help!

**Comment by mhaboali** [comment]
> Hi @navganti
> I use evo to evaluate the translation error(%) and rotation error(deg/m), but my results differ from yours in the paper of SIVO. can you tell me what evaluation tool you use？

Hi @BetterG 
How did you manage to generate those errors in percentage format using evo?
I've used it to get the values but in meters.

And could you @navganti and @BetterG explain to us how to get those values using KITTI dev kit with the first 10 sequences?

Thanks!

**Comment by olibd** [comment]
@mhaboali did you ever figure out how the percentage was aquired? I too get the values in meters.
