### ISSUE TITLE
Can I run SIVO with indoor datasets?

### ISSUE THREAD

**Issue by neocultureT** [navganti/SIVO#6]
Hello!@navganti
Thank you for sharing your work.I want to use SIVO to run indoor datasets ,and run with Segnet trained weights and models.I tested it by using kitti datasets , SUN weights and caffemodel.And I meet with this problem:CUDA out of memory.The batch size in .prototxt has been set to 2,and I don't know whether the problem is caused by the dataset not matches the weights and caffemodel,or the resolution of the images not suit for the model.

I am wondering is it feasible for SIVO to run indoor datasets?and what indoor datasets do you recommand to run for SIVO?

Looking forward to your reply!Thank you!

**Comment by navganti** [comment]
Hi @neocultureT! Sorry for the delayed response. 

I haven't actually tried to run SIVO on indoor datasets, but if your configuration files are set up properly then it shouldn't be an issue. What is the size of the images, and what GPU are you using? 

Try using the Basic network - you might have better luck getting around the memory issue.
