### ISSUE TITLE
running on cpu

### ISSUE THREAD

**Issue by Akhilelluru** [navganti/SIVO#7]
Can I run on Cpu with 16 Gb ram??

**Comment by navganti** [comment]
Hi @Akhilelluru, it will run very, very slowly if you're only using a CPU. I would try to use a higher end GPU for this implementation.

**Comment by pansyl** [comment]
hello，i running with CPU，can you tell me how should i do to make sure  build.sh pass?
error:     usr/local/include/caffe/util/device_alternate.hpp:34:23: fatal error: cublas_v2.h
