### ISSUE TITLE
batch response: This repository is over its data quota.

### ISSUE THREAD

**Issue by ghost** [navganti/SIVO#8]
Hi, @navganti 
Thank you for sharing your work, but I have trouble downloading the segbet standard model.
I am unable to clone or pull from Github because of a git-lfs quota.
When I run this command of "git lfs pull".
I got: batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. error: failed to fetch some objects from 'https://github.com/navganti/SIVO.git/info/lfs'.
Both bandwidth and storage of  my Git LFS Data are 0/1.0 GB.

Thanks.

**Comment by pansyl** [comment]
> Hi, @navganti Thank you for sharing your work, but I have trouble downloading the segbet standard model. I am unable to clone or pull from Github because of a git-lfs quota. When I run this command of "git lfs pull". I got: batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. error: failed to fetch some objects from 'https://github.com/navganti/SIVO.git/info/lfs'. Both bandwidth and storage of my Git LFS Data are 0/1.0 GB.
> 
> Thanks.

hello，i have met the same problem. How can i solve this?
